### ISSUE TITLE
Capybara not happy with filling out stripe forms

### ISSUE THREAD

**Issue by dblock** [dblock/slack-market#42]
https://travis-ci.org/dblock/slack-market

```
 1) Subscribe for a team subscribes team
     Failure/Error: page.find_field('Email').set 'foo@bar.com'
     
     Capybara::ElementNotFound:
       Unable to find field "Email"
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.12.0/lib/capybara/node/finders.rb:44:in `block in find'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.12.0/lib/capybara/node/base.rb:85:in `synchronize'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.12.0/lib/capybara/node/finders.rb:33:in `find'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.12.0/lib/capybara/node/finders.rb:79:in `find_field'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.12.0/lib/capybara/session.rb:780:in `block (2 levels) in <class:Session>'
     # ./spec/integration/subscribe_spec.rb:44:in `block (4 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.12.0/lib/capybara/session.rb:409:in `within_frame'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.12.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/integration/subscribe_spec.rb:43:in `block (3 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:15:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:98:in `cleaning'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:14:in `block (2 levels) in <top (required)>'
```

**Comment by dblock** [comment]
Seems to work for slack-gamebot. Weird.

**Comment by dblock** [comment]
Fixed in https://github.com/dblock/slack-market/commit/d835482ebb5f29838ee67b3d44f4c45d07685296.
